# This is a basic workflow that is manually triggered

name: Auto Assignb Main
on:
  pull_request:
    types: [opened, ready_for_review]
    branches: [main]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          repo-token: ${{ secrets.PAT_ACCESS_TOKEN }}
          configuration-path: '.github/auto-assign-main.yml'
